package config

import com.natpryce.konfig.Configuration
import handlers.SimpleConnectHandler
import handlers.SimpleDisconnectHandler
import handlers.SimplePublishHandler
import io.netty.handler.codec.mqtt.MqttQoS
import io.vertx.core.AsyncResult
import io.vertx.core.Handler
import io.vertx.core.Vertx
import io.vertx.ext.consul.CheckOptions
import io.vertx.ext.consul.ConsulClient
import io.vertx.ext.consul.ConsulClientOptions
import io.vertx.ext.consul.ServiceOptions
import io.vertx.mqtt.MqttClient
import io.vertx.mqtt.MqttClientOptions
import io.vertx.mqtt.messages.MqttConnAckMessage
import org.koin.core.qualifier.named
import org.koin.dsl.module
import wakeonlan.WoLClient

val serviceName = "service"

val mainModule = module {
    single{
        MqttClientOptions().apply {
            isAutoKeepAlive = true
            isAutoGeneratedClientId = true
        }
    }

    single { Vertx.vertx() }

    single {
        MqttClient.create(
            get(),
            get()
        ) as MqttClient
    }

    single {
        val config = get<Configuration>()
        ConsulClientOptions().apply {
            host = config[consulhost]
            port = config[consulport]
    } }
    
    single<ConsulClient> { ConsulClient.create(get(),get())}

    single {
        ServiceOptions()
        .setName(serviceName)
        //.setId("serviceId")
        .setTags(listOf("mqtt", "vertx"))
        .setCheckOptions(CheckOptions().setTtl("60s"))
        .setPort(1883)
    }

    single { WoLClient() }

    single(named("disconnectHandler")) { SimpleDisconnectHandler as Handler<*>}
    single(named("connectHandler")) { SimpleConnectHandler as Handler<*>}
    single(named("publishHandler")) { SimplePublishHandler as Handler<*>}

    //add topics to subscribe to
    single(named("topics")) {
        mapOf(
            "computer/+/power" to MqttQoS.AT_MOST_ONCE.value()
        )
    }
}